### ISSUE TITLE
sorti-py stops when it finds a conflict

### ISSUE THREAD

**Issue by firinael** [Tempest20/sorti-py-gui#1]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1921, in __call__
  File "sortipy_gui.py", line 27, in dir_prompt
  File "sortipy_gui.py", line 22, in sort
  File "shutil.py", line 803, in move
shutil.Error: Destination path 'C:/Users/schus/Downloads/random stuff\pdf\item.pdf' already exists
```

Would recommend adding an "overwrite/rename" dialog, if possible.

**Comment by bajramidamir** [comment]
Fixed, now the conflicting file gets renamed to item_new.ext
